import Head from "next/head";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const { id } = router.query;
  console.log(`id: ${id}`);
  const [data, setData] = useState([]);
  useEffect(() => {
    if (!router.isReady) return;
    async function getPageData() {
      const apiUrlEndpoint = "http://localhost:3000/api/getData-lib";
      const postData = {
        method: "Post",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          id: id,
        }),
      };
      const response = await fetch(apiUrlEndpoint, postData);
      const res = await response.json();
      console.log(res.members);
      setData(res.members);
    }
    getPageData();
  }, [router.query.id, router.isReady]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data.map((member) => {
        return (
          <div key={member.id}>
            {member.id} / {member.password}
          </div>
        );
      })}
    </div>
  );
}
